//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int id { get; set; }
        public string text { get; set; }
        public bool done { get; set; }
        public Nullable<System.DateTime> date_due { get; set; }
        public Nullable<System.DateTime> date_done { get; set; }
    }
}
